language: node_js
node_js:
- '0.10.21'
notifications:
  slack: odl:vToYX9UxvZZxDNtSXYG6UzCT
deploy:
  provider: heroku
  api_key:
    secure: frRR3/LviVnOlg5JyC4+L4N5YIGJjqTCAsp+c16Ax85Rjts1ZaJJLrhvUgRIFnMJo49FA7NpEAhxy6gtLSP9ewGh7ofAPHLn/Eui0m23PkWHRqz3kBuYTSFcu4Fqh12q6HLtqu7jRNNzWyzhXbU7dlFu05UlubYXTs2+TSnf5WM=
  app: odl
  on:
    repo: wearebase/odl-management-webapp
addons:
  sauce_connect:
    username: "rugbyhead"
    access_key:
      secure: "J/ObQE4OS0kt/lZhEL5VHDaPkrMQsi5BVqKMFOD9SG46xK5ATmMvaWC3NG9MNJWS72nWgfIgyKXN1rvsztyCzQC0pbMa7wYzivlyBfRuUKzkHKWJI0RjbP9hpOC+TSJppAq/TCpNz6xZaY2K1I5KXWrvsD3QbCsN7PykDhfIO30="

