language: node_js
node_js:
- '0.10'
services: mongodb
notifications:
  slack: odl:vToYX9UxvZZxDNtSXYG6UzCT
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev
  build-essential g++
before_deploy:
- git fetch --unshallow
deploy:
  strategy: git
  provider: heroku
  api_key:
    secure: VgYPTzrWd0yFXH3S7jLbCuOkxbyPVAfhUPWEofXqd7wyI/Vmvzg6Ls8y+jZIup9woi6ezf7vr+oxQGHzhXVKuB6thTHD0QlYBIhMb5X5qAxpzhDnFKS3PSUMla3ftIJkJqsvPLkMJGaO1+bsEOLeysfDHbQfWZr07i27yo/JL04=
  app: odl-uat
  on:
    repo: wearebase/odl-management-webapp
